version: '3'

services:
  express:
      build: .
      container_name: express
      ports:
        - "3004:3004"
      depends_on:
        - postgres
      links: 
        - postgres
      command: ["wait-for-it/wait-for-it.sh", "postgres:5432", "--" ,"node", "server/index.js"]


  postgres:
      image: postgres
      container_name: pg-docker
      environment:
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: reviews 
      ports:
        - "5432:5432"
      restart: always

      