version: '3'

services:
  seed:
      build: .
      container_name: seeddb
      depends_on:
        - postgres
      ports:
        - "3004:3004"
      links: 
        - postgres
      networks: 
        - service
      command: node seeddb.js

  postgres:
      image: postgres
      container_name: pg-docker
      environment:
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: reviews 
      ports:
        - "5432:5432"
      networks:
        - service
      restart: always

networks:
  service:
    driver: "bridge"

      