version: '3'

services:
  seed:
      build: .
      container_name: seeddb
      depends_on:
        - postgres
      links: 
        - postgres
      networks: 
        - service
      command: ["wait-for-it/wait-for-it.sh", "postgres:5432", "--", "node", "seeddb.js"]


  postgres:
      image: postgres
      container_name: pg-docker
      environment:
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: reviews 
      ports:
        - "5432:5432"
      networks:
        - service
      restart: always

networks:
  service:
    driver: "bridge"

      